id: I420CBCBF
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:09:35.234124
last_modified: 2023-02-09 15:09:35.234224
source_metadata:
  title: 'MSV 1,14: Poṣadhasthāpanavastu'
  language: bo
bases:
  48F8:
    base_file: 48F8.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
